### ISSUE TITLE
Little bug in "search_image"

### ISSUE THREAD

**Issue by lijin-THU** [abenassi/Google-Search-API#16]
When I run this code:
```python
from google import google
results = google.search_images("banana")
```
An `IndexError: list index out of range` occurred. 

This bug is caused by `images.py`, line `298-309`, function `_get_file_name(link)`
```python
def _get_file_name(link):

    temp_name = link.rsplit('/', 1)[1]
    image_format = _parse_image_format(link)

    if image_format and temp_name.rsplit(".", 1)[1] != image_format:
        file_name = temp_name.rsplit(".", 1)[0] + "." + image_format

    else:
        file_name = temp_name

    return file_name
```

For the "banana" image search, the problem is cause by this link: `http://vignette2.wikia.nocookie.net/donkeykong/images/1/17/BananaDKCR.png/revision/20110926232526` 

Given 
```python
link = "http://vignette2.wikia.nocookie.net/donkeykong/images/1/17/BananaDKCR.png/revision/20110926232526"
```
in `_get_file_name(link)`, we have 
```python
temp_name = "20110926232526"
image_format = "png"
```
Since `temp_name` has no `.`, `temp_name.rsplit(".", 1)` is a list of length 1 and  `temp_name.rsplit(".", 1)[1]` doesn't exist.

I think it's better to change `temp_name.rsplit(".", 1)[1]` to `temp_name.rsplit(".", 1)[-1]`, which will solve this problem.

**Comment by abenassi** [comment]
@lijin-THU  sorry by the delay in answering your issue, I have checked this out and you are totally right. It is now corrected. Txs a lot for your contribution!
