### ISSUE TITLE
No result is returned from google.search

### ISSUE THREAD

**Issue by PanWu** [abenassi/Google-Search-API#24]
I tried the following example code: 

from google import google
num_page = 3
search_results = google.search("This is my query", num_page)

However, the search_results is a empty list. Is google changing the way their page structures to disable any web scrawling?

**Comment by RyanLiuNtust** [comment]
This error seems only occur when you install by pip install....

**Comment by zodman** [comment]
+1

**Comment by lokeshh** [comment]
Has anyone found a solution yet?

**Comment by lokeshh** [comment]
Thanks @RyanLiuNtust your solution worked.

**Comment by sils** [comment]
So anything wrong with the setup.py metadata? I couldn't see anything at first glance, @abenassi , as the author, might be able to fix this rather quick.

**Comment by pseudophed** [comment]
I think this might be caused by the Python 3.4 eggs getting shipped to systems with 3.5 installed. I am also unable to get the package running by manually installing OR through pip. :(

**Comment by lsroudi** [comment]
any solytion for this issue i clonde the repo i still have the same empty list

**Comment by msfidelis** [comment]
Update PIP repository please. I need this to automate some tasks.

**Comment by abenassi** [comment]
I'm sorry for being absent of this package for quite a long time.. Fortunately I do have some more time now to catch up a bit. I have released last dev changes to PIP, but I don't think this will solve the issue...

**Comment by abenassi** [comment]
Well actually, the package is working now :-) cc @lsroudi @msfidelis @sils (last commenters)
