### ISSUE TITLE
how to google search globally 

### ISSUE THREAD

**Issue by puneetsngh** [abenassi/Google-Search-API#25]
My server is in Germany, google search api switch to german region everytime, any idea how can I switch to global search?

**Comment by omer58** [comment]
I found a workaround however it requires changing the library code:

In the package change the file in this path: google/modules/utils.py

In the following method add another field `'cr': 'countryUS'` into the dictionary named as 'params':
This is for changing the location to United States, you can do the same according to your own preference. (e.g. for Turkey it is countryTR)
```
def _get_search_url(query, page=0, per_page=10, lang='en'):
    # note: num per page might not be supported by google anymore (because of
    # google instant)

    params = {'nl': lang, 'q': query.encode(
        'utf8'), 'start': page * per_page, 'num': per_page}
    params = urlencode(params)
    url = u"http://www.google.com/search?" + params
    # return u"http://www.google.com/search?hl=%s&q=%s&start=%i&num=%i" %
    # (lang, normalize_query(query), page * per_page, per_page)
    return url
```

**Comment by Zhiwei1996** [comment]
I had added area options support
such as:  jp -> japan

**Comment by JuaniFilardo** [comment]
I tried @omer58 solution with no success, however I found a similar workaround:

In the same method (_get_search_url) add these fields to the dictionary named 'params':
` 'gl': 'us', 'pws': '0', 'gws_rd': 'cr'  `.

I'm not 100% sure, but I think that this would mean:
- 'gl': 'us' sets the Geographic Location to US
- 'pws' = '0' disables personalised search, 'gws_rd': 'cr' may
- stand for Google Web Server ReDirect: CountRy

**Comment by JuaniFilardo** [comment]
I'm closing this issue since it seems that the code I added in #45 fixes this problem.
