### ISSUE TITLE
Python3 Not Supported or Bugged?

### ISSUE THREAD

**Issue by abhishtagatya** [abenassi/Google-Search-API#49]
Due to Python 2 retiring in a year (https://pythonclock.org/), I would suggest to update this library to Python 3 so people can still use this in the future. If you have already created a Python3 version of this, please do add it in pip3 because it doesn't seem to work when I tried downloading it.

Error : 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dyjn_np3/Google-Search-API/`

Thank you for your time

**Comment by RealistikDash** [comment]
just clone the project, copy to your project directory and add from google import google to your project. Just a temporary workaround.

**Comment by abhishtagatya** [comment]
thanks for the help, i solved the problem a while back though, i should probably close this
