### ISSUE TITLE
Cannot INSTALL Please help

### ISSUE THREAD

**Issue by DavisAndhersonF** [abenassi/Google-Search-API#53]
Hello,

I'm having trouble installing this package. I use the comand:

pip install Google-Search-API    (Edit : I used sudo with no success)

but get the following error

"Command "python setup.py egg_info" failed with error code 1 in..."

I have tried

pip install --upgrade setuptools
pip install ez_setup
easy_install -U setuptools

without success. Can anyone help me on this issue?

**Comment by ansh850** [comment]
Try using sudo pip install Google-Search-API
It works for me

**Comment by RealistikDash** [comment]
just clone the project, copy to your project directory and add `from google import google` to your project. Just a temporary workaround.

**Comment by BeFede** [comment]
Hi! Your issue is an exact copy of  issue #48. Please don't repost already opened issues. 
We will try to fix this, but in the meantime you can use the solution posted by @RealistikDash.
Just clone the repo and append its path in your python project, then add `from google import google`

**Comment by JuaniFilardo** [comment]
Closing as it is the same issue as #48.
