### ISSUE TITLE
ImportError: No module named 'modules' in Windows

### ISSUE THREAD

**Issue by skvsree** [abenassi/Google-Search-API#8]
I am using Windows 10 and Anaconda python 3.4 I receive below error while trying to import 

```python
>>> from google import google
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\google\__init__.py", line 1, in <module>
    from modules import calculator, currency, images, utils
ImportError: No module named 'modules'
```

**Comment by abenassi** [comment]
Hi, the package is not written for Python 3, it supports only Python 2. You should create a virtual environment with Python 2 to use it. 

In the command line:
```
conda create -n google  python=2 anaconda
activate google
pip install Google-Search-API
```

Then you have the package installed in a `google` named environment that uses Python 2, and you can open  `ipython qtconsole` or whatever you use.
